# contains English translations for the application
# example structure

[navbar]
home = "Home"
contacts = "Contacts"
history = "History"
settings = "Settings"
alert = "Alert"


# home screen translations
[home]
a = ""

# contacts screen translations
[contacts]
a = ""

# log screen translations
[log]
a = ""

# settings screen translations
[settings]
a = ""

# alert screen translations
[alert]
a = ""