<DateCard>:
    size_hint_y: None
    height: "80dp"
    padding: "16dp", 0
    radius: self.height / 4
    style: "filled"
    theme_bg_color: "Custom"
    md_bg_color: self.bg_color
    ripple_behavior: False
    MDBoxLayout:
        orientation: "horizontal"
        spacing: "10dp"
        
        MDLabel:
            text: root.date_text
            halign: "left"
            valign: "center"
            font_style: "Title"
            role: "medium"

        MDLabel:
            text: root.time_text
            halign: "right"
            valign: "center"
            font_style: "Title"
            role: "medium"
            theme_text_color: "Secondary"


<HistoryScreen>:
    # Set the background color
    md_bg_color: app.theme_cls.backgroundColor

    MDFloatLayout:
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
        size_hint: (1, 1)


        # Fall guard text
        MDLabel:
            id: title_label
            text: app.lang.get('common', {}).get('fall_label', 'Fall Guard')
            font_style: "Display"
            role: "medium"
            bold: True
            halign: "center"
            pos_hint: {"center_x": 0.5, "center_y": 0.9}
            
            
    MDBoxLayout:
        orientation: "vertical"
        padding: "0dp", "160dp", "0dp", "0dp"
        spacing: "8dp"
        MDBoxLayout:
            id: last_falls
            padding: "16dp", "0dp", "16dp", "0dp"
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            size_hint_y: None
            height: self.minimum_height
            MDIcon:
                icon: "clock-outline"
                theme_color: "Custom"
                color: app.theme_cls.secondaryColor
                theme_font_size: "Custom"
                font_size: "32sp"
                padding: "0dp", "0dp", "16dp", "0dp"
                pos_hint: {"center_x": 0.5, "center_y": 0.75}
            MDLabel:
                text: app.lang.get('history', {}).get('no_history', 'No fall events recorded.')
                font_style: "Title"
                halign: "left"
                valign: "center"
                pos_hint: {"center_x": 0.5, "center_y": 0.75}

        MDScrollView:
            MDBoxLayout:
                id: card_container
                orientation: "vertical"
                adaptive_height: True
                padding: "16dp"
                spacing: "8dp"
        


