<HomeScreen>:
    # Set the background color
    md_bg_color: app.theme_cls.backgroundColor

    
    FloatLayout:
        size_hint: 1, 1
        pos_hint: {"center_x": 0.5, "center_y": 0.5}

        # shield icon in the center
        MDRelativeLayout:
            size_hint: 1, None
            height: self.width
            pos_hint: {"top": 1, "center_x": 0.5}
            md_bg_color: 0, 0, 0, 0

            # shield icon
            MDIcon:
                id: status_icon
                icon: "shield-lock"
                theme_color_icon: "Custom"
                color: 0, 1, 0, 1
                theme_font_size: "Custom"
                font_size: "120sp"
                pos_hint: {"center_x": 0.5, "center_y": 0.5}

