<RootLayout>:
    orientation: 'vertical'

    MDScreenManager:
        id: screen_manager
        
        HomeScreen:
            name: "home"
        
        SettingsScreen:
            name: "settings"
        
        ContactsScreen:
            name: "contacts"
        
        HistoryScreen:
            name: "history"
        
        AlertScreen:
            name: "alert_screen"
    
    # bottom navigation bar
    MDNavigationBar:
        on_switch_tabs: app.on_switch_tabs(*args)
        height: 0 if screen_manager.current == 'alert_screen' else self.width/5
        opacity: 0 if screen_manager.current == 'alert_screen' else 1
        disabled: True if screen_manager.current == 'alert_screen' else False
        # home button
        MDNavigationItem:
            tag: "home"

            MDNavigationItemIcon:
                icon: "home"
                theme_color_icon: "Custom"
                color: app.theme_cls.secondaryColor
                theme_font_size: "Custom"
                font_size: "24sp"

            MDNavigationItemLabel:
                text: app.lang.get('common', {}).get('home', 'Home')


        # contacts button
        MDNavigationItem:
            tag: "contacts"

            MDNavigationItemIcon:
                icon: "contacts"
                theme_color_icon: "Custom"
                color: app.theme_cls.secondaryColor
                theme_font_size: "Custom"
                font_size: "24sp"

            MDNavigationItemLabel:
                text: app.lang.get('common', {}).get('contacts', 'Contacts')

        # history button
        MDNavigationItem:
            tag: "history"

            MDNavigationItemIcon:
                icon: "history"
                theme_color_icon: "Custom"
                color: app.theme_cls.secondaryColor
                theme_font_size: "Custom"
                font_size: "24sp"

            MDNavigationItemLabel:
                text: app.lang.get('common', {}).get('history', 'History')

        # settings button
        MDNavigationItem:
            tag: "settings"

            MDNavigationItemIcon:
                icon: "cog"
                theme_color_icon: "Custom"
                color: app.theme_cls.secondaryColor
                theme_font_size: "Custom"
                font_size: "24sp"

            MDNavigationItemLabel:
                text: app.lang.get('common', {}).get('settings', 'Settings')